In [1]:
import pandas as pd
df = pd.read_excel('C:\\Users\\laksh\\OneDrive\\Desktop\\Lakshmi Traders\\realfile_prchase_data.xlsx')
df

,Item-Name,unit_size,unit_type,Pack-count,pack_type,unit_per_pack,category,sub-category,total_cost,Date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,Selha,10200,2026-02-15,Ram Rang Dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,chini,4400,2026-02-15,Ram Rang Dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,ashiki,8425,2026-02-15,Ram Rang Dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,Musturd Oil,5240,2026-02-15,Ram Rang Dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,Refined,21400,2026-02-15,Ram Rang Dealer
...,...,...,...,...,...,...,...,...,...,...,...
194,amrit khada,1.0,pkt,20,pkt,1.0,Spices,tatri,900,2026-01-12,Raju Brothers
195,soya,15.0,kg,5,tin,1.0,Oil,Refined,10650,2026-01-12,Raju Brothers
196,ravindra,15.0,kg,3,tin,1.0,Oil,Musturd Oil,6690,2026-01-12,Raju Brothers
197,bhusi dal,30.0,kg,1,bag,1.0,Grain,arhar dal,2220,2026-01-12,Raju Brothers
198,matar,30.0,kg,2,bag,1.0,Grain,matar,2820,2026-01-12,Raju Brothers

In [2]:
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True,format='mixed',errors='coerce')
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('-','_')
df.head()

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,sub_category,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,Selha,10200,2026-02-15,Ram Rang Dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,chini,4400,2026-02-15,Ram Rang Dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,ashiki,8425,2026-02-15,Ram Rang Dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,Musturd Oil,5240,2026-02-15,Ram Rang Dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,Refined,21400,2026-02-15,Ram Rang Dealer

In [3]:
df.groupby('category')['total_cost'].sum() # total purchase category wise.

category
Chinese        3890
Dry Fruit     61275
Flour         63755
Grain         93720
Oil          306379
Other         11400
Rice          46476
Snacks         1560
Spices        18724
Sugar         81490
Tobacco       39990
detergent      5490
pooja         18700
Name: total_cost, dtype: int64

In [4]:
df.groupby('supplier')['total_cost'].sum() # total purchase supplier wise

supplier
Raju Brothers             148490
Ram Rang Dealer           284358
Shyamu Trading Company    320001
Name: total_cost, dtype: int64

In [5]:
df.insert(7,'total_quantity', df['unit_per_pack']*df['pack_count']*df['unit_size']) # Add a column for total quantity of a item 
df.head()

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,10200,2026-02-15,Ram Rang Dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,4400,2026-02-15,Ram Rang Dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,8425,2026-02-15,Ram Rang Dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,5240,2026-02-15,Ram Rang Dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,21400,2026-02-15,Ram Rang Dealer

In [6]:
df.insert(9,'cost_per_unit',round(df['total_cost']/df['total_quantity'],2)) # Add a column to find per unit price
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,2026-02-15,Ram Rang Dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,2026-02-15,Ram Rang Dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,2026-02-15,Ram Rang Dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,2026-02-15,Ram Rang Dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,2026-02-15,Ram Rang Dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,amrit khada,1.0,pkt,20,pkt,1.0,Spices,20.0,tatri,45.00,900,2026-01-12,Raju Brothers
195,soya,15.0,kg,5,tin,1.0,Oil,75.0,Refined,142.00,10650,2026-01-12,Raju Brothers
196,ravindra,15.0,kg,3,tin,1.0,Oil,45.0,Musturd Oil,148.67,6690,2026-01-12,Raju Brothers
197,bhusi dal,30.0,kg,1,bag,1.0,Grain,30.0,arhar dal,74.00,2220,2026-01-12,Raju Brothers
198,matar,30.0,kg,2,bag,1.0,Grain,60.0,matar,47.00,2820,2026-01-12,Raju Brothers

In [7]:
df.insert(11,'month',df['date'].dt.strftime('%b'))
df.head(10)

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,Ram Rang Dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,Ram Rang Dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,Ram Rang Dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,Ram Rang Dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,Ram Rang Dealer
5,chana bada,30.0,kg,1,bag,1.0,Grain,30.0,chana,67.00,2010,Feb,2026-02-15,Ram Rang Dealer
6,aata,50.0,kg,2,bag,1.0,Flour,100.0,aata,29.40,2940,Feb,2026-02-15,Ram Rang Dealer
7,aata,26.0,kg,2,bag,1.0,Flour,52.0,aata,30.19,1570,Feb,2026-02-15,Ram Rang Dealer
8,chini,50.0,kg,5,bag,1.0,Sugar,250.0,chini,43.20,10800,Feb,2026-02-15,Ram Rang Dealer
9,surajmukhi,1.0,pkt,1,bag,115.0,Tobacco,115.0,surjamukhi,36.09,4150,Feb,2026-02-15,Ram Rang Dealer

In [8]:
Q1 = df['cost_per_unit'].quantile(0.25)
Q3 = df['cost_per_unit'].quantile(0.75)
IQR = Q3-Q1

In [9]:
df_clean = df[
    (df['cost_per_unit']>= Q1 - 1.5*IQR)&
    (df['cost_per_unit']<= Q3 + 1.5*IQR)
]

In [10]:
median_rate = df.groupby(['item_name','unit_size','pack_type'])['cost_per_unit'].median()
df["median_rate"] = df.set_index(
    ["item_name","unit_size","pack_type"]
).index.map(median_rate)
df[['item_name','cost_per_unit','median_rate']]

        item_name  cost_per_unit  median_rate
0         DM Rice          85.00       85.000
1    seema powder         176.00      176.000
2          Ashiki          80.24       78.000
3          Arohul         174.67      174.670
4         fortune         142.67      142.335
..            ...            ...          ...
194   amrit khada          45.00       45.000
195          soya         142.00      142.000
196      ravindra         148.67      148.670
197     bhusi dal          74.00       77.000
198         matar          47.00       47.000

[199 rows x 3 columns]

In [11]:
df['rate_deviation'] = round(df['cost_per_unit']/df['median_rate'],2)
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier,median_rate,rate_deviation
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,Ram Rang Dealer,85.000,1.00
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,Ram Rang Dealer,176.000,1.00
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,Ram Rang Dealer,78.000,1.03
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,Ram Rang Dealer,174.670,1.00
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,Ram Rang Dealer,142.335,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,amrit khada,1.0,pkt,20,pkt,1.0,Spices,20.0,tatri,45.00,900,Jan,2026-01-12,Raju Brothers,45.000,1.00
195,soya,15.0,kg,5,tin,1.0,Oil,75.0,Refined,142.00,10650,Jan,2026-01-12,Raju Brothers,142.000,1.00
196,ravindra,15.0,kg,3,tin,1.0,Oil,45.0,Musturd Oil,148.67,6690,Jan,2026-01-12,Raju Brothers,148.670,1.00
197,bhusi dal,30.0,kg,1,bag,1.0,Grain,30.0,arhar dal,74.00,2220,Jan,2026-01-12,Raju Brothers,77.000,0.96
198,matar,30.0,kg,2,bag,1.0,Grain,60.0,matar,47.00,2820,Jan,2026-01-12,Raju Brothers,47.000,1.00

In [12]:
def label(x):
    if x > 1.1:
        return "Overvalued"
    elif x < 0.9:
        return "Undervalued"
    else:
        return "Normal"

df["rate_status"] = df["rate_deviation"].apply(label)

In [13]:
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier,median_rate,rate_deviation,rate_status
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,Ram Rang Dealer,85.000,1.00,Normal
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,Ram Rang Dealer,176.000,1.00,Normal
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,Ram Rang Dealer,78.000,1.03,Normal
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,Ram Rang Dealer,174.670,1.00,Normal
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,Ram Rang Dealer,142.335,1.00,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,amrit khada,1.0,pkt,20,pkt,1.0,Spices,20.0,tatri,45.00,900,Jan,2026-01-12,Raju Brothers,45.000,1.00,Normal
195,soya,15.0,kg,5,tin,1.0,Oil,75.0,Refined,142.00,10650,Jan,2026-01-12,Raju Brothers,142.000,1.00,Normal
196,ravindra,15.0,kg,3,tin,1.0,Oil,45.0,Musturd Oil,148.67,6690,Jan,2026-01-12,Raju Brothers,148.670,1.00,Normal
197,bhusi dal,30.0,kg,1,bag,1.0,Grain,30.0,arhar dal,74.00,2220,Jan,2026-01-12,Raju Brothers,77.000,0.96,Normal
198,matar,30.0,kg,2,bag,1.0,Grain,60.0,matar,47.00,2820,Jan,2026-01-12,Raju Brothers,47.000,1.00,Normal

In [14]:
df.loc[df['sub_category']=='pista']

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier,median_rate,rate_deviation,rate_status
69,pista,0.25,kg,1,pkt,4.0,Dry Fruit,1.0,pista,950.0,950,Jan,2026-01-12,Shyamu Trading Company,950.0,1.0,Normal

In [15]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
password = quote_plus('Luckygupt@1990')

engine = create_engine(f"postgresql://postgres:{password}@localhost:5432/lakshmi_shop_database")
df.to_sql('purchases',engine,if_exists='replace',index=False)
print('saved file in sql.')

saved file in sql.