In [62]:
import pandas as pd
df = pd.read_excel('C:\\Users\\laksh\\OneDrive\\Desktop\\Lakshmi Traders\\realfile_prchase_data.xlsx')
df

,Item-Name,unit_size,unit_type,Pack-count,pack_type,unit_per_pack,category,sub-category,total_cost,Date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,Selha,10200,2026-02-15,ram rang dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,chini,4400,2026-02-15,ram rang dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,ashiki,8425,2026-02-15,ram rang dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,Musturd Oil,5240,2026-02-15,ram rang dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,Refined,21400,2026-02-15,ram rang dealer
...,...,...,...,...,...,...,...,...,...,...,...
108,mahakosh,4.0,kg,1,gatta,4.0,Oil,Refined,2760,2026-01-31,Shyamu trading company
109,BL,1.0,kg,1,gatta,20.0,Oil,Musturd Oil,2640,2026-01-31,Shyamu trading company
110,urad daal,30.0,kg,1,bag,1.0,Grain,Urad dal,3900,2026-01-31,Shyamu trading company
111,navrang,2.0,kg,1,pkt,1.0,Other,color,500,2026-01-31,Shyamu trading company
112,Kamla,1.0,pkt,25,pkt,39.0,Tobacco,kamla,5300,2026-03-17,ram rang dealer

In [63]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('-','_')
df.head()

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,sub_category,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,Selha,10200,2026-02-15,ram rang dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,chini,4400,2026-02-15,ram rang dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,ashiki,8425,2026-02-15,ram rang dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,Musturd Oil,5240,2026-02-15,ram rang dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,Refined,21400,2026-02-15,ram rang dealer

In [64]:
df.groupby('category')['total_cost'].sum() # total purchase category wise.

category
Chinese        2150
Dry Fruit     37400
Flour         34100
Grain         59790
Oil          210342
Other          4130
Rice          37220
Snacks         1560
Sugar         55450
Tobacco       27575
pooja          6350
Name: total_cost, dtype: int64

In [65]:
df.groupby('supplier')['total_cost'].sum() # total purchase supplier wise

supplier
Shyamu trading company    237840
ram rang dealer           238227
Name: total_cost, dtype: int64

In [66]:
df.insert(7,'total_quantity', df['unit_per_pack']*df['pack_count']*df['unit_size']) # Add a column for total quantity of a item 
df.head()

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,10200,2026-02-15,ram rang dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,4400,2026-02-15,ram rang dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,8425,2026-02-15,ram rang dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,5240,2026-02-15,ram rang dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,21400,2026-02-15,ram rang dealer

In [67]:
df.insert(9,'cost_per_unit',round(df['total_cost']/df['total_quantity'],2)) # Add a column to find per unit price
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,2026-02-15,ram rang dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,2026-02-15,ram rang dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,2026-02-15,ram rang dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,2026-02-15,ram rang dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,2026-02-15,ram rang dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,mahakosh,4.0,kg,1,gatta,4.0,Oil,16.0,Refined,172.50,2760,2026-01-31,Shyamu trading company
109,BL,1.0,kg,1,gatta,20.0,Oil,20.0,Musturd Oil,132.00,2640,2026-01-31,Shyamu trading company
110,urad daal,30.0,kg,1,bag,1.0,Grain,30.0,Urad dal,130.00,3900,2026-01-31,Shyamu trading company
111,navrang,2.0,kg,1,pkt,1.0,Other,2.0,color,250.00,500,2026-01-31,Shyamu trading company
112,Kamla,1.0,pkt,25,pkt,39.0,Tobacco,975.0,kamla,5.44,5300,2026-03-17,ram rang dealer

In [68]:
df.insert(11,'month',df['date'].dt.strftime('%b'))
df.head(10)

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,ram rang dealer
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,ram rang dealer
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,ram rang dealer
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,ram rang dealer
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,ram rang dealer
5,chana bada,30.0,kg,1,bag,1.0,Grain,30.0,chana,67.00,2010,Feb,2026-02-15,ram rang dealer
6,aata,50.0,kg,2,bag,1.0,Flour,100.0,aata,29.40,2940,Feb,2026-02-15,ram rang dealer
7,aata,26.0,kg,2,bag,1.0,Flour,52.0,aata,30.19,1570,Feb,2026-02-15,ram rang dealer
8,chini,50.0,kg,5,bag,1.0,Sugar,250.0,chini,43.20,10800,Feb,2026-02-15,ram rang dealer
9,surajmukhi,1.0,pkt,1,bag,115.0,Tobacco,115.0,surjamukhi,36.09,4150,Feb,2026-02-15,ram rang dealer

In [69]:
Q1 = df['cost_per_unit'].quantile(0.25)
Q3 = df['cost_per_unit'].quantile(0.75)
IQR = Q3-Q1

In [70]:
df_clean = df[
    (df['cost_per_unit']>= Q1 - 1.5*IQR)&
    (df['cost_per_unit']<= Q3 + 1.5*IQR)
]

In [71]:
median_rate = df.groupby(['item_name','unit_size','pack_type'])['cost_per_unit'].median()
df["median_rate"] = df.set_index(
    ["item_name","unit_size","pack_type"]
).index.map(median_rate)
df[['item_name','cost_per_unit','median_rate']]

        item_name  cost_per_unit  median_rate
0         DM Rice          85.00       85.000
1    seema powder         176.00      176.000
2          Ashiki          80.24       80.240
3          Arohul         174.67      174.670
4         fortune         142.67      142.335
..            ...            ...          ...
108      mahakosh         172.50      172.500
109            BL         132.00      132.000
110     urad daal         130.00      130.000
111       navrang         250.00      250.000
112         Kamla           5.44        5.605

[113 rows x 3 columns]

In [72]:
df['rate_deviation'] = round(df['cost_per_unit']/df['median_rate'],2)
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier,median_rate,rate_deviation
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,ram rang dealer,85.000,1.00
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,ram rang dealer,176.000,1.00
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,ram rang dealer,80.240,1.00
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,ram rang dealer,174.670,1.00
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,ram rang dealer,142.335,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,mahakosh,4.0,kg,1,gatta,4.0,Oil,16.0,Refined,172.50,2760,Jan,2026-01-31,Shyamu trading company,172.500,1.00
109,BL,1.0,kg,1,gatta,20.0,Oil,20.0,Musturd Oil,132.00,2640,Jan,2026-01-31,Shyamu trading company,132.000,1.00
110,urad daal,30.0,kg,1,bag,1.0,Grain,30.0,Urad dal,130.00,3900,Jan,2026-01-31,Shyamu trading company,130.000,1.00
111,navrang,2.0,kg,1,pkt,1.0,Other,2.0,color,250.00,500,Jan,2026-01-31,Shyamu trading company,250.000,1.00
112,Kamla,1.0,pkt,25,pkt,39.0,Tobacco,975.0,kamla,5.44,5300,Mar,2026-03-17,ram rang dealer,5.605,0.97

In [73]:
def label(x):
    if x > 1.1:
        return "Overvalued"
    elif x < 0.9:
        return "Undervalued"
    else:
        return "Normal"

df["rate_status"] = df["rate_deviation"].apply(label)

In [74]:
df

,item_name,unit_size,unit_type,pack_count,pack_type,unit_per_pack,category,total_quantity,sub_category,cost_per_unit,total_cost,month,date,supplier,median_rate,rate_deviation,rate_status
0,DM Rice,30.0,kg,4,bag,1.0,Rice,120.0,Selha,85.00,10200,Feb,2026-02-15,ram rang dealer,85.000,1.00,Normal
1,seema powder,25.0,kg,1,bag,1.0,Sugar,25.0,chini,176.00,4400,Feb,2026-02-15,ram rang dealer,176.000,1.00,Normal
2,Ashiki,1.0,pkt,3,bag,35.0,Tobacco,105.0,ashiki,80.24,8425,Feb,2026-02-15,ram rang dealer,80.240,1.00,Normal
3,Arohul,15.0,kg,2,tin,1.0,Oil,30.0,Musturd Oil,174.67,5240,Feb,2026-02-15,ram rang dealer,174.670,1.00,Normal
4,fortune,15.0,kg,10,tin,1.0,Oil,150.0,Refined,142.67,21400,Feb,2026-02-15,ram rang dealer,142.335,1.00,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,mahakosh,4.0,kg,1,gatta,4.0,Oil,16.0,Refined,172.50,2760,Jan,2026-01-31,Shyamu trading company,172.500,1.00,Normal
109,BL,1.0,kg,1,gatta,20.0,Oil,20.0,Musturd Oil,132.00,2640,Jan,2026-01-31,Shyamu trading company,132.000,1.00,Normal
110,urad daal,30.0,kg,1,bag,1.0,Grain,30.0,Urad dal,130.00,3900,Jan,2026-01-31,Shyamu trading company,130.000,1.00,Normal
111,navrang,2.0,kg,1,pkt,1.0,Other,2.0,color,250.00,500,Jan,2026-01-31,Shyamu trading company,250.000,1.00,Normal
112,Kamla,1.0,pkt,25,pkt,39.0,Tobacco,975.0,kamla,5.44,5300,Mar,2026-03-17,ram rang dealer,5.605,0.97,Normal